'✨ 30 minutes':
  - '(?i)- \[x\]\s*30\s*minutes?'
'🔥 1 heure':
  - '(?i)- \[x\]\s*1\s*heure'
'☀️ 1 heure et demi':
  - '(?i)- \[x\]\s*1\s*heure\s*(et)?\s*demi'
'⏳ Durée libre':
  - '(?i)- \[x\]\s*(autre|autres?),?\s*(précisez|precisez)\s*:'